### PR TITLE
Adding StaffService Class

### PR DESCRIPTION
**Pull request by daniel-fitzg**
Adding StaffService class to service all non-manager employee operations/classes.

*Minor change:
- Moved employeeDataStore and validationService class variables to EmployeeService class.

### CODE REVIEW

**Review by rdmoraes — APPROVED** [review]
Looks good for me, just not sure why you change the access modifiers from private to package-private in EmployeeDataStoreService and ValidationService

**Comment by daniel-fitzg** [comment]
@rdmoraes Those two variables were moved to EmployeeService because both are used in ManagerService and StaffService. No point in having the variables repeat. But If they are private in EmployeeService then the ManagerService and StaffService classes can't access them. Classes that inherit from others can't access private fields and methods.

I suppose it's a design question. What is better for us? Extra variables and keep them private in each class, or one set of variables but make package private. What do you think?

**Comment by rdmoraes** [comment]
I think adding an extra var just for that would make the code more difficult to understand, but leaving the classes package-private as you did is the better to go.

**Comment by dshirt** [comment]
Looks good to me too

**Review by dshirt — APPROVED** [review]

**Pull request merged**
